
/**************************************************************
 *	
 *	alert, 8 bit, 44100Hz,
 *	1 channel, 41472 bytes/channel
 *	Total Size: 1 * 41472 + 4 (header) = 41516 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\alert.wav
 *	Time-stamp: Tue Nov 18 18:03:56 2014
 *	
 **************************************************************/

#ifndef __ALERTH__
#define __ALERTH__

#define ALERTFREQ 44100
#define ALERTLEN 41472

extern const unsigned char alert[41472];

#endif /* __ALERTH__ */
