
/**************************************************************
 *	
 *	Ballad, 8 bit, 44100Hz,
 *	1 channel, 4231296 bytes/channel
 *	Total Size: 1 * 4231296 + 4 (header) = 4231340 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\Ballad.wav
 *	Time-stamp: Wed Nov 26 23:10:43 2014
 *	
 **************************************************************/

#ifndef __BALLADH__
#define __BALLADH__

#define BALLADFREQ 44100
#define BALLADLEN 4231296

extern const unsigned char Ballad[4231296];

#endif /* __BALLADH__ */
