
/**************************************************************
 *	
 *	crash0, 8 bit, 48000Hz,
 *	1 channel, 70647 bytes/channel
 *	Total Size: 1 * 70647 + 4 (header) = 70691 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\crash0.wav
 *	Time-stamp: Sat Nov 01 15:23:25 2014
 *	
 **************************************************************/

#ifndef __CRASH0H__
#define __CRASH0H__

#define CRASH0FREQ 48000
#define CRASH0LEN 70647

extern const unsigned char crash0[70647];

#endif /* __CRASH0H__ */
