
/**************************************************************
 *	
 *	crash, 8 bit, 44100Hz,
 *	1 channel, 23804 bytes/channel
 *	Total Size: 1 * 23804 + 4 (header) = 23848 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\crash.wav
 *	Time-stamp: Sat Nov 01 15:23:30 2014
 *	
 **************************************************************/

#ifndef __CRASHH__
#define __CRASHH__

#define CRASHFREQ 44100
#define CRASHLEN 23804

extern const unsigned char crash[23804];

#endif /* __CRASHH__ */
