
/**************************************************************
 *	
 *	explosion, 8 bit, 44100Hz,
 *	1 channel, 112896 bytes/channel
 *	Total Size: 1 * 112896 + 4 (header) = 112940 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\explosion.wav
 *	Time-stamp: Sat Nov 29 13:50:06 2014
 *	
 **************************************************************/

#ifndef __EXPLOSIONH__
#define __EXPLOSIONH__

#define EXPLOSIONFREQ 44100
#define EXPLOSIONLEN 112896

extern const unsigned char explosion[112896];

#endif /* __EXPLOSIONH__ */
