
/**************************************************************
 *	
 *	expl02, 8 bit, 44100Hz,
 *	1 channel, 124416 bytes/channel
 *	Total Size: 1 * 124416 + 4 (header) = 124460 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\expl02.wav
 *	Time-stamp: Sat Nov 29 13:21:57 2014
 *	
 **************************************************************/

#ifndef __EXPL02H__
#define __EXPL02H__

#define EXPL02FREQ 44100
#define EXPL02LEN 124416

extern const unsigned char expl02[124416];

#endif /* __EXPL02H__ */
