
/**************************************************************
 *	
 *	expl03, 8 bit, 44100Hz,
 *	1 channel, 130176 bytes/channel
 *	Total Size: 1 * 130176 + 4 (header) = 130220 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\expl03.wav
 *	Time-stamp: Sat Nov 29 13:21:52 2014
 *	
 **************************************************************/

#ifndef __EXPL03H__
#define __EXPL03H__

#define EXPL03FREQ 44100
#define EXPL03LEN 130176

extern const unsigned char expl03[130176];

#endif /* __EXPL03H__ */
