
/**************************************************************
 *	
 *	expl01, 8 bit, 44100Hz,
 *	1 channel, 125568 bytes/channel
 *	Total Size: 1 * 125568 + 4 (header) = 125612 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\expl01.wav
 *	Time-stamp: Sat Nov 29 13:22:00 2014
 *	
 **************************************************************/

#ifndef __EXPL01H__
#define __EXPL01H__

#define EXPL01FREQ 44100
#define EXPL01LEN 125568

extern const unsigned char expl01[125568];

#endif /* __EXPL01H__ */
