
/**************************************************************
 *	
 *	longCrash, 8 bit, 48000Hz,
 *	1 channel, 209152 bytes/channel
 *	Total Size: 1 * 209152 + 4 (header) = 209196 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\longCrash.wav
 *	Time-stamp: Tue Nov 18 18:03:53 2014
 *	
 **************************************************************/

#ifndef __LONGCRASHH__
#define __LONGCRASHH__

#define LONGCRASHFREQ 48000
#define LONGCRASHLEN 209152

extern const unsigned char longCrash[209152];

#endif /* __LONGCRASHH__ */
