
/**************************************************************
 *	
 *	playerShot, 8 bit, 44100Hz,
 *	1 channel, 19404 bytes/channel
 *	Total Size: 1 * 19404 + 4 (header) = 19448 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\playerShot.wav
 *	Time-stamp: Sat Nov 01 15:23:22 2014
 *	
 **************************************************************/

#ifndef __PLAYERSHOTH__
#define __PLAYERSHOTH__

#define PLAYERSHOTFREQ 44100
#define PLAYERSHOTLEN 19404

extern const unsigned char playerShot[19404];

#endif /* __PLAYERSHOTH__ */
