
/**************************************************************
 *	
 *	Powerup8, 8 bit, 44100Hz,
 *	1 channel, 20310 bytes/channel
 *	Total Size: 1 * 20310 + 4 (header) = 20354 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\Powerup8.wav
 *	Time-stamp: Sat Nov 01 21:46:12 2014
 *	
 **************************************************************/

#ifndef __POWERUP8H__
#define __POWERUP8H__

#define POWERUP8FREQ 44100
#define POWERUP8LEN 20310

extern const unsigned char Powerup8[20310];

#endif /* __POWERUP8H__ */
