
/**************************************************************
 *	
 *	Powerup6, 8 bit, 44100Hz,
 *	1 channel, 22082 bytes/channel
 *	Total Size: 1 * 22082 + 4 (header) = 22126 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Stephanie\Dropbox\Files of College\CS2261\wav2c\Powerup6.wav
 *	Time-stamp: Sat Nov 01 21:46:15 2014
 *	
 **************************************************************/

#ifndef __POWERUP6H__
#define __POWERUP6H__

#define POWERUP6FREQ 44100
#define POWERUP6LEN 22082

extern const unsigned char Powerup6[22082];

#endif /* __POWERUP6H__ */
